kind: pipeline
type: docker
name: alpine

steps:
- name: build
  image: alpine:edge
  commands:
  - apk update
  - apk add bash make gcc g++ musl-dev libpng-dev jpeg-dev tiff-dev git
  - apk add octave octave-dev
  - git clone https://github.com/mnhrdt/iio
  - make -C iio/contrib/octave
  - echo "addpath('$PWD/iio/contrib/octave');" >$HOME/.octaverc
  - ./olambda
  - bash tests/test.sh

---
kind: pipeline
type: docker
name: archlinux

steps:
- name: build
  image: archlinux
  commands:
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm make gcc libpng libtiff libjpeg git octave
  - git clone https://github.com/mnhrdt/iio
  - make -C iio/contrib/octave
  - echo "addpath('$PWD/iio/contrib/octave');" >$HOME/.octaverc
  - ./olambda
  - bash tests/test.sh

---
kind: pipeline
type: docker
name: ubuntu-latest

steps:
- name: build
  image: ubuntu:latest
  commands:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -qq build-essential git octave liboctave-dev
  - apt-get install -qq libpng-dev libtiff-dev libjpeg-dev
  - git clone https://github.com/mnhrdt/iio
  - make -C iio/contrib/octave
  - echo "addpath('$PWD/iio/contrib/octave');" >$HOME/.octaverc
  - ./olambda
  - bash tests/test.sh

---
kind: pipeline
type: docker
name: ubuntu-rolling

steps:
- name: build
  image: ubuntu:rolling
  commands:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -qq build-essential git octave liboctave-dev
  - apt-get install -qq libpng-dev libtiff-dev libjpeg-dev
  - git clone https://github.com/mnhrdt/iio
  - make -C iio/contrib/octave
  - echo "addpath('$PWD/iio/contrib/octave');" >$HOME/.octaverc
  - ./olambda
  - bash tests/test.sh

